### ISSUE TITLE
Change attributes on error gone from image processor?

### ISSUE THREAD

**Issue by gfxguru** [dweeves/magmi-git#198]
This is a much needed feature and no longer available correct? It's not on my configuration setting for Image attributes processor v1.0.33... Anyone else confirm?

**Comment by dweeves** [comment]
fixed in latest commit

**Comment by mserbanoiu** [comment]
Change attributes on error still not working on the latest version  - image processor 1.0.33a - I have no options to setup attribute
