### ISSUE TITLE
Magmi stuck while importing CSV

### ISSUE THREAD

**Issue by farazhkhan** [dweeves/magmi-git#436]
Linux: CentOS 7.2 
Magento: CE 1.9.0.1 
Magmi: 0.7.22 
Nginx: 1.8.1 
PHP: 5.6.19 
MySQL: 5.6.29 
Varnish: 4.0.3 
Redis: 3.0.7

We did run a perfect installation of Magmi as instructed and assigned proper permissions to files(even tried with 777), but for some reason our Magmi import stuck exactly at 2449 items (2.4%) like this

![magmi_stuck](https://cloud.githubusercontent.com/assets/12461099/14160172/241d217a-f6f4-11e5-8e58-2d65f730ed87.PNG)

No matter which CSV we select, what permissions we assign to CSV's(even 777) but it always stuck at the same point 2.4%!

We restarted all services and purged all cache just in case there could be something stuck somewhere, but nothing help. We even tried to use file based sessions and cache and stopped Redis but no luck. We thought there could be a latest version of Magmi in Git 0.7.23 https://github.com/dweeves/magmi-git which may have addressed this kind of issue but still no luck. Also, we tried checking PHP-FPM log, Nginx log, MySQL log and other logs but nothing is being reported anywhere expect some usual warnings like time zone but nothing related to Magmi. we reinstalled Magmi several times but no luck!

The strange part is that on same server we have another site with exactly same configuration where Magmi is working fine, from there we tried to import the same CSV and it worked, this proves there is no issue with CSV structure and nothing on server level.

Can someone guide us what could be the issue and where do we need to look to troubleshoot?

**Comment by mithunb** [comment]
I am having the exact same problem.

**Comment by dweeves** [comment]
In this case, it may be a php fatal error that occur when importing one
line.

Could you find anything in the apache logs ? maybe you should also try
launching the same import via command line to see what might happen.

Maybe a trace.txt file has also been generated in magmi/state directory to
investigate.

2016-04-01 13:33 GMT+02:00 mithunb <notifications@github.com>:

**Comment by mithunb** [comment]
Here is some more information about the UI stall. The UI works fine with the same CSV on a similar set-up on the staging server (update: the CSV stopped working here too). On the production and staging, CLI works correctly. While running from UI, progress.txt is opened but not closed and stalls at around 4%.

Also, the UI was working correctly when it was installed for the first time but eventually stopped working. CSVs that used to worked earlier have stopped working.

CSV contains simple and configurable products. 


Startup Info:
Running Magmi Product Import Engine v1.9.1 by dweeves
Import Profile:K1Live
Import Mode:update
Attributeset update is enabled.
Magmi Magento Reindexer v1.0.3a - Using execution mode :popen
Performing Datasource Lookup...
Found 396 records, took 0.032859086990356 sec
Configurable Item processor v1.3.7a - no options_container set, defaulting to :Block after product info
Ajusted processed columns:66

Runtime Info:
Magmi Optimizer v1.0.5 - Optimizing magmi
Magmi Optimizer v1.0.5 - Adding index MAGMI_EAOV_OPTIMIZATION_IDX on eav_attribute_option_value
Magmi Optimizer v1.0.5 - Already optmized!
Magmi Optimizer v1.0.5 - Adding index MAGMI_CPEM_OPTIMIZATION_IDX on catalog_product_entity_media_gallery
Magmi Optimizer v1.0.5 - Already optmized!
Magmi Optimizer v1.0.5 - Adding index MAGMI_CCEV_OPTIMIZATION_IDX on catalog_category_entity_varchar
Magmi Optimizer v1.0.5 - Already optmized!
Magmi Optimizer v1.0.5 - Adding index MAGMI_EA_CODE_OPTIMIZATION_IDX on eav_attribute
Magmi Optimizer v1.0.5 - Already optmized!
Initialized attribute_set_infos!

Magmistate says running.

**Comment by farazhkhan** [comment]
@dweeves In magmi/state folder following exists

> 
> 0       dummy.txt
> 4.0K    magmistate
> 256K    progress.txt
> 4.0K    timings.txt
> 0       trace.txt

Which means nothing there in **trace.txt** and **magmistate** contains text 

> idle

For logs, as I am running Nginx+PHP-FPM there is nothing in the log at all.

**Comment by mithunb** [comment]
Looked in the apache error log and found the problem. Increased memory and that solved the problem. Thanks.

**Comment by farazhkhan** [comment]
One thing I noticed that when I run from command line it works fine. So, yes it could be memory issue, but where? do I need to adjust something in php.ini or somewhere else in Nginx?

**Comment by patvdleer** [comment]
Any updates on this one? Running into the same problem...

**Comment by mithunb** [comment]
Mine got solved by increasing php memory limit for Apache.

On 29 Aug 2016 9:22 p.m., "Patrick van der Leer" <notifications@github.com>
wrote:

>

> Any updates on this one? Running into the same problem...
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
<https://github.com/dweeves/magmi-git/issues/436#issuecomment-243165749>, or
mute the thread

**Comment by patvdleer** [comment]
Limit is set to 512MB with a CSV of ~ 600KB but still no luck. I am running on PHP7 but I'm not getting any errors. The ajax call keeps running and returning 200.

**Comment by mithunb** [comment]
I remember I had to go all the way to 1.5gb to get it to work.

**Comment by patvdleer** [comment]
2GB, still no luck

**Comment by dweeves** [comment]
This is surely not  a memory issue. Magmi is very low on memory consumption

If it works on command line, then maybe the problem is due to some php-fpm
configuration (if you are using php-fpm), and also, magmi UI is launching a
long running request in AJAX to perform import.

If your max executiuon time is set to 30s , then magmi "long running"
import request will be killed by your web server, letting the UI in a
"never ending" mode.





2016-08-30 13:46 GMT+02:00 Patrick van der Leer <notifications@github.com>:

**Comment by patvdleer** [comment]
I'm using Apache2 with mod_php7 so not the FPM, the long running thingies seem to take a few ms followed by a short pause. I haven't tried to run it via cli but I will and get back to you on that.

**Comment by patvdleer** [comment]
CLI gives me issue #480

**Comment by dweeves** [comment]
Set your "report step" (in general settings) to something > to 0.  Maybe
PHP7 has some different behaviour for magmi code parsing this value and
returns 0.


2016-08-30 15:39 GMT+02:00 Patrick van der Leer <notifications@github.com>:

**Comment by patvdleer** [comment]
Awesome that fixed it!

**Comment by bignick44** [comment]
Im having the same issue here..
Im running on a php 5.6, so can this sulotion work for me to?
And where can i config: "Report step" (in general settings)??

Thank you!

**Comment by metacognizance** [comment]
![alt text](http://i.imgur.com/rOvy2a9.png "Reporting step in %")

**Comment by HOSTED-POWER** [comment]
Hi,

It's indeed also a compatibility error with php 7.0. 

Division by zero exception, while before no exception. Should be fixed in code :)

**Comment by thomas-harding** [comment]
I was having trouble running imports (got stuck at 0%).

Setting reporting step to 1 (as per screenshot) worked for me 👍

**Comment by r1tt3r** [comment]
When I try to run the import, it hangs at 0%. So I checked in the PHP logs, which showed me the following:

> [11-Jan-2019 12:24:50 UTC] PHP Fatal error:  Call to a member function getVersion() on null in /usr/share/nginx/decorainteriores/www/magmi-git/magmi/plugins/extra/general/remoteagent/008_magmi_remoteagent_plugin.php on line 35


Any idea what that might be?

**Comment by alikarli** [comment]
I was having trouble running imports (got stuck at 85.8%).

Setting reporting step to 1 (as per screenshot) worked for me 👍

with this setup prosess.txt file size not growing fast..

**Comment by inickca** [comment]
hi

I did 1 upload of 3500 line, no problem, next, i try 100 line, exact same config, and all i get is this : 

https://pasteboard.co/I8iEyJu.png

I have try with 5 others files, same error., I did change step to 1 or 5 but no change.

any idea ?

**Comment by Alan-Luna-Carreon** [comment]
Hi!

In my case, I had the option Import email notification v1.0.0 checked. After unchecking it, MAGMI started working fine.

I have MAGMI  v0.7.22 working on Magento 1.9.3.8

**Comment by Henrik41** [comment]
it's 2022... and I am having the same issue.
