### ISSUE TITLE
'price' Update Issue

### ISSUE THREAD

**Issue by ne0nlight** [dweeves/magmi-git#517]
Hey guys!

So, when doing a Magmi Import to a product with 'price' included, whilst looking through the product catalog in the backend of Magento, it will appear as if the product hasn't been changed (price stays as old price) along with looking at the product in a category view. 

However, if going into the product in the backend, OR going to the product page in front end, you will now see the proper price. And if you save the product while in backend, it will save the new price to where it can be seen everywhere properly.

Any idea why this happens and how it can be done to import the new price and have it working in all areas? Thanks!

**Comment by Reflektorfalke** [comment]
Hey,

have you performed a Re-Index after import?
(Or have "Magmi Magento Reindexer" Plugin enabled on import)

That should fix the issue and show updated price also in frontend category view.

Cheers

**Comment by ne0nlight** [comment]
Hey Reflektorfalke,

Yes I have re-indexed the pricing after import via backend (not the Magmi reindexer) but the issue persists, any ideas?

**Comment by Reflektorfalke** [comment]
Re-Indexed only product prices index?
Probably also re-index for product flat data index is required for update price everywhere.
Or go for a full re-index (which is what Magmi reindexer would do) to verify its indeed an issue with indexes and not related to something else (e. g. some cache, FPC etc.)

**Comment by ne0nlight** [comment]
Thanks for continued support!

I generally do a full re-index when indexing, so I have re-Indexed everything along with clearing the cache however the issue continues. I've experienced this for a while as I would just edit in back-end catalog view and just one by one click to edit the price (immediately the false price automatically replaces with new price and then hit enter) and we're back to it all being as it should be. Was a quick fix, however as the catalog grows this could become a time consuming issue, so here I am!

**Comment by Reflektorfalke** [comment]
Hm, am afraid have no further ideas.
From my experience, magmi import updates showing correctly in backend, but not in frontend, have always been an issue with index and/or cache.
Guess with your case a more detailed debugging regarding import config, import file or even customizations in magento would be neeed to find the issue.

**Comment by ne0nlight** [comment]
I'll try and do more digging as to what the culprit can be, thanks for the help!
